baseURL = "https://jeffdalley.com/"
languageCode = "en-us"
title = "Jeff Dalley - Developer of Things"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "darkorange"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["c#", "css", "javascript", "go"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://twitter.com/jeffdalley/"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jdalley/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://stackoverflow.com/users/30598/jeff-dalley"
    name = "stack-overflow"
    weight = 3
